#!/usr/bin/env sh
set -eu

root="${1:-.}"

test -f "$root/README.md"
test -d "$root/src/vkfwd"
test -d "$root/src/vkfwd/ferry"
test -d "$root/src/vkfwd/facade"
test -d "$root/src/third_party"
test -d "$root/dev/test/internal-test"
test -d "$root/dev/third_party"
test -d "$root/dev/env"
test -d "$root/dev/bin"
test -d "$root/src/vkfwd/ferry/script/generator"
test -f "$root/src/vkfwd/ferry/forwarder/layer.cpp"
test -f "$root/src/vkfwd/ferry/forwarder/forwarder.hpp"
test -f "$root/src/vkfwd/ferry/forwarder/forwarder.cpp"
test -f "$root/src/vkfwd/ferry/forwarder/manifest/VK_LAYER_VKFWD_forwarder.json.in"
test -f "$root/src/vkfwd/ferry/core/protocol.hpp"
test -f "$root/src/vkfwd/ferry/core/generated/vulkan_manifest.json"
test -f "$root/src/vkfwd/ferry/core/generated/vulkan_coverage.md"
test -f "$root/src/vkfwd/ferry/core/generated/vulkan_api.hpp"
test -f "$root/src/vkfwd/ferry/core/generated/vulkan_manual_hooks.hpp"
test -f "$root/src/vkfwd/ferry/core/generated/README.md"
test -f "$root/src/vkfwd/ferry/core/generated/command/vkCreateInstance.metadata.json"
test -f "$root/src/vkfwd/ferry/core/generated/command/vkCreateInstance.hpp"
test -f "$root/src/vkfwd/ferry/core/generated/command/vkCreateInstance.cpp"
test -f "$root/src/vkfwd/ferry/core/generated/command/vkCreateDevice.metadata.json"
test -f "$root/src/vkfwd/ferry/core/generated/command/vkCreateDevice.hpp"
test -f "$root/src/vkfwd/ferry/core/generated/command/vkCreateDevice.cpp"
test -f "$root/src/vkfwd/ferry/forwarder/generated/dispatch_table.hpp"
test -f "$root/src/vkfwd/ferry/forwarder/generated/dispatch_table.cpp"
test -f "$root/src/vkfwd/ferry/forwarder/generated/vulkan_forwarder_hooks.hpp"
test -f "$root/src/vkfwd/ferry/forwarder/generated/command/vkCreateInstance.cpp"
test -f "$root/src/vkfwd/ferry/forwarder/generated/command/vkCreateDevice.cpp"
test -f "$root/src/vkfwd/ferry/core/hook/README.md"
test -f "$root/src/vkfwd/ferry/core/hook/vkCreateDeviceHook.hpp"
test -f "$root/src/vkfwd/ferry/core/hook/vkCreateDeviceHook.cpp"
test -f "$root/src/vkfwd/ferry/receiver/receiver.hpp"
test -f "$root/src/vkfwd/ferry/receiver/receiver.cpp"
