#!/usr/bin/env sh
set -eu

root="${1:-.}"

test -f "$root/README.md"
test -d "$root/src/vkfwd"
test -d "$root/src/third_party"
test -d "$root/dev/test"
test -d "$root/dev/env"
test -d "$root/dev/bin"
test -d "$root/dev/generator"
test -f "$root/src/vkfwd/layer.cpp"
test -f "$root/src/vkfwd/protocol.hpp"
test -f "$root/src/vkfwd/generated/vulkan_manifest.json"
test -f "$root/src/vkfwd/generated/vulkan_coverage.md"
test -f "$root/src/vkfwd/generated/vulkan_api.hpp"
test -f "$root/src/vkfwd/generated/vulkan_api.cpp"
test -f "$root/src/vkfwd/generated/vulkan_manual_hooks.hpp"
test -f "$root/src/vkfwd/generated/README.md"
test -f "$root/src/vkfwd/generated/commands/vkCreateInstance.metadata.json"
test -f "$root/src/vkfwd/generated/commands/vkCreateInstance.hpp"
test -f "$root/src/vkfwd/generated/commands/vkCreateInstance.cpp"
test -f "$root/src/vkfwd/generated/commands/vkCreateDevice.metadata.json"
test -f "$root/src/vkfwd/generated/commands/vkCreateDevice.hpp"
test -f "$root/src/vkfwd/generated/commands/vkCreateDevice.cpp"
test -f "$root/src/vkfwd/hooks/README.md"
test -f "$root/src/vkfwd/hooks/vkCreateDeviceHooks.hpp"
test -f "$root/src/vkfwd/hooks/vkCreateDeviceHooks.cpp"
