#!/usr/bin/env sh
set -eu

root="${1:-.}"

test -f "$root/README.md"
test -d "$root/src/vkfwd"
test -d "$root/src/third_party"
test -d "$root/dev/test"
test -d "$root/dev/env"
test -d "$root/dev/bin"
test -d "$root/dev/generator"
test -f "$root/src/vkfwd/forwarder/layer.cpp"
test -f "$root/src/vkfwd/forwarder/forwarder.hpp"
test -f "$root/src/vkfwd/forwarder/forwarder.cpp"
test -f "$root/src/vkfwd/forwarder/manifest/VK_LAYER_VKFWD_forwarder.json.in"
test -f "$root/src/vkfwd/core/protocol.hpp"
test -f "$root/src/vkfwd/core/generated/vulkan_manifest.json"
test -f "$root/src/vkfwd/core/generated/vulkan_coverage.md"
test -f "$root/src/vkfwd/core/generated/vulkan_api.hpp"
test -f "$root/src/vkfwd/core/generated/vulkan_api.cpp"
test -f "$root/src/vkfwd/core/generated/vulkan_manual_hooks.hpp"
test -f "$root/src/vkfwd/core/generated/README.md"
test -f "$root/src/vkfwd/core/generated/command/vkCreateInstance.metadata.json"
test -f "$root/src/vkfwd/core/generated/command/vkCreateInstance.hpp"
test -f "$root/src/vkfwd/core/generated/command/vkCreateInstance.cpp"
test -f "$root/src/vkfwd/core/generated/command/vkCreateDevice.metadata.json"
test -f "$root/src/vkfwd/core/generated/command/vkCreateDevice.hpp"
test -f "$root/src/vkfwd/core/generated/command/vkCreateDevice.cpp"
test -f "$root/src/vkfwd/core/hook/README.md"
test -f "$root/src/vkfwd/core/hook/vkCreateDeviceHook.hpp"
test -f "$root/src/vkfwd/core/hook/vkCreateDeviceHook.cpp"
test -f "$root/src/vkfwd/receiver/receiver.hpp"
test -f "$root/src/vkfwd/receiver/receiver.cpp"
